language: go
go: 
 - 1.7.3

install:
 - pwd

script:
 - go test -race $(go list ./... | grep -v /vendor/)

after_success:
 - curl --request POST "https://goreportcard.com/checks" --data "repo=github.com/artemnikitin/cci"
